### ISSUE TITLE
Comments on DSNB flat flux?

### ISSUE THREAD

**Issue by haradamasayuki** [SKSNSim/SKSNSim#35]
When I execute DSNB mode using `--flatposflux` option, below message are appeared. But the events are properly generated.
> Ignore this message if you do NOT use flat-flux mode.
https://github.com/SKSNSim/SKSNSim/blob/1f1e5ccbfff6f765c05d8126aeba842dd2664afd/main_dsnb.cc#L86
https://github.com/SKSNSim/SKSNSim/blob/1f1e5ccbfff6f765c05d8126aeba842dd2664afd/main_dsnb.cc#L87

Perhaps this message is for using model-flux mode?

**Comment by shotaizu** [comment]
Yes, it is originally impelemented to convert the number of generated events to the abosolute flux value.
In the SKSNSim, the flux are impelemented with the pair of energy and flux. However, user generates events as users want, by specifying number of events to be generated. This output originally shows the absolute scale between the number of generated events and the flux value (e.g. flux = 1E-40 /sec/MeV at energy = 3.0 MeV, the indicated value is used to number of generated events to the scale of 1E-40 /sec/MeV). Internally, it is calculated by the hit-and-miss method's efficiency of random number throw.

In case of `--flatposflux` option, the abosolute scale has no mean. So, I put that message.
